<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;
/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function listAllCategories()
    {
        return $this->getEntityManager()
            ->createQueryBuilder(
                'SELECT c FROM AppBundle:Category c ORDER BY c.name ASC'
            );
    }
}
