<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Institution;
use Doctrine\ORM\EntityRepository;

/**
 * InstitutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionRepository extends EntityRepository
{
    public function listAllInstitutions()
    {
        return $this->getEntityManager()
            ->createQueryBuilder(
                'SELECT i FROM AppBundle:Institution i ORDER BY i.name ASC'
            );
    }

    public function getInstitutionsOrderedByDonations()
    {
        return $this->getEntityManager()->createQueryBuilder('i')
            ->select('i, d')
            ->from('AppBundle:Institution', 'i')
            ->join('i.donations', 'd')
            ->orderBy('d.quantity')
            ->getQuery()
            ->getResult();
    }

    public function getTotalNumberOfOrgs()
    {
        return $this->getEntityManager()->createQueryBuilder('i')
            ->select('count(i)')
            ->from('AppBundle:Institution', 'i')
            ->getQuery()
            ->getSingleScalarResult();
    }

}
